backend:
  name: github
  repo: joj0s/sb-website
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dyeki9pps
    api_key: 455689789792114

collections:
  - name: "members"
    label: "Member"
    folder: "content/members"
    create: true
    slug: "{{name}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Designation"
        name: "designation"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
        config:
          default_transformations:
            - fetch_format: auto
              width: 250
              quality: auto
              crop: fill
      - label: "Social Links"
        name: "socialLinks"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "GitHub link", name: "github", widget: "string", required: false}
          - {label: "GitLab link", name: "gitlab", widget: "string", required: false}
          - {label: "Facebook link", name: "facebook", widget: "string", required: false}
          - {label: "Instagram link", name: "instagram", widget: "string", required: false}
          - {label: "LinkedIn link", name: "linkedin", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "events"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{question}}"
    fields:
      - {label: "Event Title", name: "title", widget: "string"}
      - {label: "Event Description", name: "description", widget: "text"}
      - {label: "Event Image", name: "image", widget: "image", media_folder: "/uploads/events"}
      - {label: "Event Date", name: "date", widget: "datetime"}
      - {label: "Facebook link", name: "fbLink", widget: "string"}
      - {label: "Youtube link", name: "ytLink", widget: "string", required: false}
  - name: "faq"
    label: "Faq"
    folder: "content/faq"
    create: true
    slug: "{{question}}"
    fields:
      - {label: "Question", name: "question", widget: "string"}
      - {label: "Answer", name: "answer", widget: "text"}
