backend:
  name: github
  repo: joj0s/sb-website
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dyeki9pps
    api_key: 455689789792114

collections:
  - name: "members"
    label: "Member"
    folder: "content/members"
    create: true
    slug: "{{name}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Designation"
        name: "designation"
        widget: "string"
        default: "Member"
      - label: "Image"
        name: "image"
        widget: "image"
        config:
          default_transformations:
            - fetch_format: auto
              width: 250
              quality: auto
              crop: fill
      - label: "Social Links"
        name: "socialLinks"
        widget: "object"
        collapsed: true
        fields:
          - {
              label: "GitHub link",
              name: "github",
              widget: "string",
              required: false,
              default: "#",
            }
          - {
              label: "GitLab link",
              name: "gitlab",
              widget: "string",
              required: false,
              default: "#",
            }
          - {
              label: "Facebook link",
              name: "facebook",
              widget: "string",
              required: false,
              default: "#",
            }
          - {
              label: "Instagram link",
              name: "instagram",
              widget: "string",
              required: false,
              default: "#",
            }
          - {
              label: "LinkedIn link",
              name: "linkedin",
              widget: "string",
              required: false,
              default: "#",
            }
      - { label: "Publish Date", name: "date", widget: "datetime" }
  - name: "events"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{title}}"
    fields:
      - label: "Event Title"
        name: "title"
        widget: "string"
      - label: "Event Description"
        name: "description"
        pattern: ['.{,450}', "Maximum length is 450 characters."]
        widget: "text"
      - label: "Event Image"
        name: "image"
        widget: "image"
        config:
          default_transformations:
            - fetch_format: auto
              width: 320
              height: 180
              quality: auto
              crop: fill
      - label: "Event Date"
        name: "date"
        widget: "datetime"
      - label: "Facebook link"
        name: "fbLink"
        widget: "string"
        required: false
        default: "#"
        hint: "If you want no link to appear, insert '#' as the value."
      - label: "Youtube link"
        name: "ytLink"
        widget: "string"
        required: false
        default: "#"
        hint: "If you want no link to appear, insert '#' as the value."
  - name: "faq"
    label: "Faq"
    folder: "content/faq"
    create: true
    slug: "{{question}}"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - {
          label: "Question Order",
          name: "order",
          value_type: "int",
          hint: "Order in which you want the question to appear in FAQ section",
        }
      - { label: "Answer", name: "body", widget: "markdown" }
  - name: "galleryImage"
    label: "Gallery Image"
    folder: "content/gallery"
    create: true
    slug: "{{caption}}-{{id}}"
    fields:
      - label: "Image"
        name: "image"
        widget: "image"
        config:
          default_transformations:
            - fetch_format: auto
              width: 1024
              height: 480
              quality: auto
              crop: fill
      - label: "Caption"
        name: "caption"
        widget: "string"
